version: '3.8'

services:
  vexfs:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/your-org/vexfs:latest
    ports:
      - "8080:8080"  # VexFS Unified Server (ChromaDB + Qdrant + Native APIs)
      - "3000:3000"  # VexFS Dashboard
    environment:
      - RUST_LOG=info
      - PORT=8080
      - DASHBOARD_PORT=3000
      - VEXFS_DATA_DIR=/app/data
    volumes:
      - vexfs_data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  # Production setup with nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - vexfs
    restart: unless-stopped
    profiles:
      - production

volumes:
  vexfs_data:
    driver: local