# VexFS v2 Qdrant Adapter Docker Compose

version: '3.8'

services:
  vexfs-qdrant-adapter:
    build: .
    container_name: vexfs-qdrant-adapter
    ports:
      - "6333:6333"  # Qdrant API port
      - "8000:8000"  # Metrics port
    environment:
      - VEXFS_DEVICE_PATH=/dev/vexfs_v2_phase3
      - API_HOST=0.0.0.0
      - API_PORT=6333
      - LOG_LEVEL=INFO
      - PERF_ENABLE_METRICS=true
      - PERF_METRICS_PORT=8000
    volumes:
      - /dev/vexfs_v2_phase3:/dev/vexfs_v2_phase3  # Mount VexFS device
      - ./logs:/app/logs  # Mount logs directory
    devices:
      - /dev/vexfs_v2_phase3:/dev/vexfs_v2_phase3  # Device access
    privileged: true  # Required for kernel module access
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: vexfs-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    depends_on:
      - vexfs-qdrant-adapter
    profiles:
      - monitoring

  # Optional: Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: vexfs-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    profiles:
      - monitoring

volumes:
  grafana-storage:

networks:
  default:
    name: vexfs-network