apiVersion: v2
name: vexfs
description: A Helm chart for VexFS - Vector Extended File System
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/vexfs/vexfs
sources:
  - https://github.com/vexfs/vexfs
maintainers:
  - name: VexFS Contributors
    email: maintainers@vexfs.org
keywords:
  - filesystem
  - vector
  - embeddings
  - similarity-search
  - database
annotations:
  category: Database
  licenses: Apache-2.0
dependencies:
  - name: prometheus
    version: "25.8.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
  - name: grafana
    version: "7.0.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled