apiVersion: v1
kind: Service
metadata:
  name: {{ include "vexfs.fullname" . }}
  labels:
    {{- include "vexfs.labels" . | nindent 4 }}
  {{- with .Values.vexfs.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.vexfs.service.type }}
  ports:
    - port: {{ .Values.vexfs.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "vexfs.selectorLabels" . | nindent 4 }}