apiVersion: v1
kind: Service
metadata:
  name: vexfs-qdrant-adapter
  namespace: vexfs-qdrant-adapter
  labels:
    app: vexfs-qdrant-adapter
    component: vector-database
    tier: production
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
  ports:
  - name: http-api
    port: 6333
    targetPort: http-api
    protocol: TCP
  - name: grpc-api
    port: 6334
    targetPort: grpc-api
    protocol: TCP
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
  selector:
    app: vexfs-qdrant-adapter
    tier: production
---
apiVersion: v1
kind: Service
metadata:
  name: vexfs-qdrant-adapter-internal
  namespace: vexfs-qdrant-adapter
  labels:
    app: vexfs-qdrant-adapter
    component: vector-database
    tier: production
    service-type: internal
spec:
  type: ClusterIP
  ports:
  - name: http-api
    port: 6333
    targetPort: http-api
    protocol: TCP
  - name: grpc-api
    port: 6334
    targetPort: grpc-api
    protocol: TCP
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
  - name: metrics-export
    port: 9090
    targetPort: metrics-export
    protocol: TCP
  selector:
    app: vexfs-qdrant-adapter
    tier: production
---
apiVersion: v1
kind: Service
metadata:
  name: vexfs-qdrant-adapter-headless
  namespace: vexfs-qdrant-adapter
  labels:
    app: vexfs-qdrant-adapter
    component: vector-database
    tier: production
    service-type: headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-api
    port: 6333
    targetPort: http-api
    protocol: TCP
  - name: grpc-api
    port: 6334
    targetPort: grpc-api
    protocol: TCP
  selector:
    app: vexfs-qdrant-adapter
    tier: production